import type { Metadata } from 'next';
import React from 'react';

import { inter } from '@/common/components/font/Inter';

import { CoreLayout } from '@/common/components/CoreLayout';

import '@/common/styles/globals.css';

export const metadata: Metadata = {
    title: 'Did I Win Toto?',
    description: 'Generated by create next app'
};

export default function RootLayout({
    children
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <CoreLayout>{children}</CoreLayout>
            </body>
        </html>
    );
}
