export enum SystemType {
    ORDINARY = 'ORDINARY',
    SYSTEM7 = 'SYSTEM7',
    SYSTEM8 = 'SYSTEM8',
    SYSTEM9 = 'SYSTEM9',
    SYSTEM10 = 'SYSTEM10',
    SYSTEM11 = 'SYSTEM11',
    SYSTEM12 = 'SYSTEM12',
    SYSTEMROLL = 'SYSTEMROLL'
}
