name: Toto Scraper Workflow

on:
    schedule:
        - cron: '0 0 * * *' # Run daily at midnight UTC
    workflow_dispatch: # Allow manual trigger

env:
    DATABASE_URL: ${{ secrets.DATABASE_URL }}

jobs:
    call-scrape:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Use Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '20'

            - name: Install pnpm
              uses: pnpm/action-setup@v2
              with:
                  version: 9.6.0 

            - name: Install dependencies
              run: pnpm install --no-frozen-lockfile

            - name: Load prisma schema
              run: npx prisma generate
            
            - name: Check db url
              run: echo ${DATABASE_URL}
            
            - name: Scrape TOTO results
              run: pnpm run build

            - name: Commit and push
              run: |
                  git config user.name "github-actions"
                  git config user.email "github-actions@github.com"
                  git add .
                  git commit -m "Automated Toto Scrape"
                  git push
