name: Toto Scraper Workflow

on:
    schedule:
        - cron: '0 0 * * *' # Run daily at midnight UTC
    workflow_dispatch: # Allow manual trigger

jobs:
    call-scrape:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Use Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '20'

            - name: Install pnpm
              uses: pnpm/action-setup@v2
              with:
                  version: 9.6.0  

            - name: Install dependencies
              run: pnpm install

            - name: Scrape TOTO results
              run: pnpm build

            - name: Check for changes
              id: git-check
              run: |
                  git status --porcelain
                  echo "changes=$(git status --porcelain | wc -l)" >> $GITHUB_OUTPUT

            - name: Commit and push if changes exist
              if: steps.git-check.outputs.changes > 0
              run: |
                  git config user.name "${{ secrets.NAME }}"
                  git config user.email "${{ secrets.EMAIL }}"
                  git add .
                  git commit -m "Automatated Toto Scrape"
                  git push
